import os
import html
import shutil

BASE_DIR = 'learning-java/src'
OUTPUT_DIR = 'website_out'

def create_page(path, title, content_html, is_index=False):
    # 90s Documentation Style CSS
    style = """
    <style>
        body { font-family: "Courier New", Courier, monospace; line-height: 1.5; color: #000; background: #fff; margin: 20px; }
        .container { max-width: 1000px; border: 1px solid #000; padding: 20px; }
        .header { border-bottom: 2px solid #000; margin-bottom: 20px; padding-bottom: 10px; }
        .nav { margin-bottom: 20px; font-weight: bold; }
        pre { background: #eeeeee; border: 1px solid #999; padding: 15px; overflow: auto; font-size: 13px; }
        ul { list-style-type: square; }
        a { color: #0000FF; }
        a:visited { color: #551A8B; }
        .folder-block { margin-bottom: 30px; border: 1px inset #ccc; padding: 10px; }
        .footer { margin-top: 30px; font-size: 11px; border-top: 1px solid #000; padding-top: 10px; }
    </style>
    """
    
    breadcrumb = ""
    if not is_index:
        breadcrumb = '<div class="nav"><a href="index.html">[UP TO MAIN DIRECTORY]</a></div>'

    html_template = f"""
    <html>
    <head><title>{title}</title>{style}</head>
    <body>
        <div class="container">
            <div class="header">
                <h1>{title}</h1>
            </div>
            {breadcrumb}
            {content_html}
            <div class="footer">
                Generated by DSA Auto-Build System
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(os.path.join(OUTPUT_DIR, path), 'w', encoding='utf-8') as f:
        f.write(html_template)

def build_structure():
    if os.path.exists(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR)
    os.makedirs(OUTPUT_DIR)

    repo_structure = {}
    
    if not os.path.exists(BASE_DIR):
        print(f"Error: {BASE_DIR} not found")
        return

    # 1. Map the structure
    for root, dirs, files in os.walk(BASE_DIR):
        rel_path = os.path.relpath(root, BASE_DIR)
        valid_files = [f for f in files if f.endswith(('.java', '.cpp', '.py', '.txt'))]
        if valid_files:
            repo_structure[rel_path] = sorted(valid_files)

    # 2. Generate Code Pages
    for folder, files in repo_structure.items():
        for file in files:
            file_path = os.path.join(BASE_DIR, folder, file) if folder != '.' else os.path.join(BASE_DIR, file)
            
            with open(file_path, 'r', encoding='utf-8') as f:
                code_content = html.escape(f.read())
            
            # Create a unique HTML file for this code
            page_filename = f"{folder}_{file}.html".replace('.', '_').replace('/', '_').replace('\\', '_') + ".html"
            code_html = f"<h2>File: {file}</h2><pre><code>{code_content}</code></pre>"
            create_page(page_filename, f"DOCUMENT: {file}", code_html)

    # 3. Generate Index Page
    index_html = "<h2>PROJECT INDEX</h2>"
    for folder in sorted(repo_structure.keys()):
        display_folder = folder if folder != "." else "ROOT"
        index_html += f'<div class="folder-block"><strong>DIRECTORY: {display_folder}</strong><ul>'
        for file in repo_structure[folder]:
            page_link = f"{folder}_{file}.html".replace('.', '_').replace('/', '_').replace('\\', '_') + ".html"
            index_html += f'<li><a href="{page_link}">{file}</a></li>'
        index_html += "</ul></div>"

    create_page("index.html", "DSA MASTER ARCHIVE", index_html, is_index=True)

if __name__ == "__main__":
    build_structure()
