name: Build and Deploy DSA Site
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # ADD THESE PERMISSIONS HERE
    permissions:
      contents: write
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Site Files
        run: |
          python build_site.py

      - name: Deploy to Separate Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website_out 
          branch: gh-pages
          clean: true
